version: '3'

services:
  hugo:
    image: klakegg/hugo:0.101.0-ext-alpine
    container_name: hugoed2
    command: server
    entrypoint: hugo
    volumes:
      - "./hugo:/src"
    ports:
      - "1313:1313"
    networks:
      - mylocal
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    networks:
      - mylocal
  rabbit:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mylocal
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - mylocal
  kafka:
      image: wurstmeister/kafka:latest
      container_name: kafka
      ports:
        - "9092:9092"
      expose:
        - "9093"
      environment:
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
        KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      depends_on:
        - zookeeper
      networks:
        - mylocal
networks:
  mylocal:
    external: true