version: "3"

services:
  nginxgeo:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mylocal
  geo1:
    build: .
    networks:
      - mylocal
    env_file:
      - ../.env
  geo2:
    build: .
    networks:
      - mylocal
    env_file:
      - ../.env
  geo3:
    build: .
    networks:
      - mylocal
    env_file:
      - ../.env
  redis:
    image: redis
    networks:
      - mylocal
networks:
  mylocal:
    external: true